/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_portfolio_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_portfolio_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_portfolio_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_api_portfolio_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/performance/year/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance For Year */
        get: operations["performance_for_year_api_portfolio_performance_year__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/performance/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Periods */
        get: operations["performance_periods_api_portfolio_performance_periods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/performance/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Methodology */
        get: operations["performance_methodology_api_portfolio_performance_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Growth */
        get: operations["portfolio_growth_api_portfolio_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/growth/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Growth Summary */
        get: operations["portfolio_growth_summary_api_portfolio_growth_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/growth/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Growth Reconciliation */
        get: operations["portfolio_growth_reconciliation_api_portfolio_growth_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["holdings_api_portfolio_holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/holdings/{code}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holding History */
        get: operations["holding_history_api_portfolio_holdings__code__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allocation */
        get: operations["allocation_api_portfolio_allocation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/allocation/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allocation History */
        get: operations["allocation_history_api_portfolio_allocation_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/concentration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concentration */
        get: operations["concentration_api_portfolio_concentration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income */
        get: operations["income_api_portfolio_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/income/yield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income Yield */
        get: operations["income_yield_api_portfolio_income_yield_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/income/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income Growth */
        get: operations["income_growth_api_portfolio_income_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contributions */
        get: operations["contributions_api_portfolio_contributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/contributions/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contributions History */
        get: operations["contributions_history_api_portfolio_contributions_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/gains/realised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Realised Gains */
        get: operations["realised_gains_api_portfolio_gains_realised_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/gains/unrealised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unrealised Gains */
        get: operations["unrealised_gains_api_portfolio_gains_unrealised_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attribution */
        get: operations["attribution_api_portfolio_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/attribution/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security Attribution */
        get: operations["security_attribution_api_portfolio_attribution_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/attribution/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attribution Reconciliation */
        get: operations["attribution_reconciliation_api_portfolio_attribution_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk */
        get: operations["risk_api_portfolio_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/risk/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Benchmark */
        get: operations["risk_benchmark_api_portfolio_risk_benchmark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/drawdowns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drawdowns */
        get: operations["drawdowns_api_portfolio_drawdowns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/drawdowns/high-water-mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** High Water Mark */
        get: operations["high_water_mark_api_portfolio_drawdowns_high_water_mark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/risk/rolling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rolling */
        get: operations["rolling_api_portfolio_risk_rolling_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_portfolio_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/best-worst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Best Worst */
        get: operations["best_worst_api_portfolio_best_worst_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Milestones */
        get: operations["milestones_api_portfolio_milestones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description A presentation of existing Phase 1/2 transaction records -- not a new
         *     transaction engine (sec 27). Sorted most recent first.
         */
        get: operations["activity_api_portfolio_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityRow */
        ActivityRow: {
            /** Transaction Id */
            transaction_id: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Type */
            type: string;
            /** Code */
            code?: string | null;
            /** Units */
            units?: string | null;
            /** Price */
            price?: string | null;
            /** Net Amount */
            net_amount?: string | null;
            /** Description */
            description: string;
        };
        /**
         * AllocationHistoryPoint
         * @description One bucket of history.allocation_history() -- weights and normalised
         *     percentages through time, keyed by security code or asset class
         *     depending on `by` (sec 8's allocation family, history variant).
         */
        AllocationHistoryPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total */
            total: string;
            /** Weights */
            weights: {
                [key: string]: string;
            };
            /** Allocation Pct */
            allocation_pct: {
                [key: string]: string | null;
            };
        };
        /**
         * AllocationResult
         * @description getAllocation(). `status` is "unavailable" for a dimension the source
         *     data can't support (sector/geography/currency) -- weights/allocation_pct
         *     are then absent entirely, never an empty-but-present dict that could be
         *     mistaken for "zero of everything" (sec 9).
         */
        AllocationResult: {
            /** By */
            by: string;
            /** Status */
            status: string;
            /** Date */
            date?: string | null;
            /** Total */
            total?: string | null;
            /** Weights */
            weights?: {
                [key: string]: string;
            } | null;
            /** Allocation Pct */
            allocation_pct?: {
                [key: string]: string | null;
            } | null;
            /** Note */
            note?: string | null;
        };
        /** AttributionCapitalAppreciation */
        AttributionCapitalAppreciation: {
            /** Total */
            total: string;
            /** Securities */
            securities: {
                [key: string]: string;
            };
        };
        /**
         * AttributionCash
         * @description Cash is represented explicitly in the tree (Phase 4 hardening sec 5)
         *     -- never silently excluded just because it isn't a security. data_quality
         *     is "unavailable" rather than the fields being absent, when cash's own
         *     contribution genuinely cannot be computed.
         */
        AttributionCash: {
            /** Interest Income */
            interest_income?: string | null;
            /** Fees */
            fees?: string | null;
            /** Profit */
            profit?: string | null;
            /** Data Quality */
            data_quality: string;
        };
        /** AttributionIncome */
        AttributionIncome: {
            /** Dividends */
            dividends: string;
            /** Distributions */
            distributions: string;
            /** Interest */
            interest: string;
        };
        /** AttributionInvestmentReturn */
        AttributionInvestmentReturn: {
            /** Total */
            total: string;
            capital_appreciation: components["schemas"]["AttributionCapitalAppreciation"];
            income: components["schemas"]["AttributionIncome"];
        };
        /** AttributionPeriod */
        AttributionPeriod: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /**
         * AttributionReconciliationPair
         * @description getGrowthReconciliation()/getAttributionReconciliation() reported
         *     together -- two independent reconciliations of the same period, kept
         *     distinct rather than merged into one figure (sec 8/hardening sec 3).
         */
        AttributionReconciliationPair: {
            growth: components["schemas"]["ReconciliationResult"];
            attribution: components["schemas"]["ReconciliationResult"];
        };
        /** AttributionTree */
        AttributionTree: {
            period: components["schemas"]["AttributionPeriod"];
            /** External Cash Flows */
            external_cash_flows: string;
            investment_return: components["schemas"]["AttributionInvestmentReturn"];
            cash: components["schemas"]["AttributionCash"];
            /** Fees */
            fees: string;
            /** Taxes */
            taxes: string;
            /** Other Adjustments */
            other_adjustments: string;
        };
        /**
         * BenchmarkComparison
         * @description Portfolio-vs-benchmark (sec 11/23). Every field is None/absent when
         *     no benchmark is registered -- the frontend must never construct a
         *     fake comparison from a missing one.
         */
        BenchmarkComparison: {
            /** Portfolio Return */
            portfolio_return?: string | null;
            /** Benchmark Return */
            benchmark_return?: string | null;
            /** Relative Return */
            relative_return?: string | null;
            /** Portfolio Methodology */
            portfolio_methodology: string;
            /** Benchmark Methodology */
            benchmark_methodology?: string | null;
            /** Methodology Mismatch */
            methodology_mismatch: boolean;
            /** Status */
            status: string;
            /** Note */
            note?: string | null;
            /** Benchmark Id */
            benchmark_id?: string | null;
            /** Benchmark Name */
            benchmark_name?: string | null;
            /** Benchmark Return Method */
            benchmark_return_method?: string | null;
            /** Benchmark Data Source */
            benchmark_data_source?: string | null;
            /** Benchmark Frequency */
            benchmark_frequency?: string | null;
            /** Benchmark Coverage */
            benchmark_coverage?: number | null;
        };
        /** CalendarPerformanceRow */
        CalendarPerformanceRow: {
            /** Period */
            period: string;
            /** Twrr */
            twrr?: string | null;
            /** Xirr */
            xirr?: string | null;
            /** Income */
            income: string;
            /** Contributions */
            contributions: string;
            /** Withdrawals */
            withdrawals: string;
            /** Closing Value */
            closing_value?: string | null;
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "actual" | "calculated" | "estimated" | "unavailable";
        };
        /**
         * Capability
         * @description One entry in getAnalyticsCapabilities() (sec 6): whether a metric can
         *     be shown, and why not when it can't. The frontend must never infer this
         *     from absent data -- both fields are always present.
         */
        Capability: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /**
         * CashFlowEvent
         * @description One contribution or withdrawal, traceable back to its own source
         *     transaction_id (sec 11: data provenance) -- the same id
         *     /api/portfolio/activity already surfaces for this transaction.
         */
        CashFlowEvent: {
            /** Transaction Id */
            transaction_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Type
             * @enum {string}
             */
            type: "CONTRIBUTION" | "WITHDRAWAL";
            /** Amount */
            amount: string;
            /** Account */
            account: string;
            /** Source */
            source: string;
            /** Description */
            description?: string | null;
        };
        /** ConcentrationSnapshot */
        ConcentrationSnapshot: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Largest Holding Pct */
            largest_holding_pct?: string | null;
            /** Top 5 Pct */
            top_5_pct?: string | null;
            /** Top 10 Pct */
            top_10_pct?: string | null;
            /** Herfindahl Index */
            herfindahl_index?: string | null;
            /** Holding Count */
            holding_count: number;
        };
        /**
         * ContributionHistoryRow
         * @description One bucket of history.contribution_history() -- per-period flows plus
         *     running totals (sec 8's contributions family, history variant).
         */
        ContributionHistoryRow: {
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Contributions */
            contributions: string;
            /** Withdrawals */
            withdrawals: string;
            /** Net Contributions */
            net_contributions: string;
            /** Cumulative Contributions */
            cumulative_contributions: string;
            /** Cumulative Withdrawals */
            cumulative_withdrawals: string;
            /** Cumulative Net */
            cumulative_net: string;
        };
        /** ContributionSummary */
        ContributionSummary: {
            /** Total Contributed */
            total_contributed: string;
            /** Total Withdrawn */
            total_withdrawn: string;
            /** Net Contributed */
            net_contributed: string;
            /** Investment Growth */
            investment_growth?: string | null;
            /** Income Received */
            income_received: string;
            /** Current Value */
            current_value?: string | null;
            /**
             * As At
             * Format: date
             */
            as_at: string;
        };
        /**
         * DataCoverage
         * @description getDataCoverage() (sec 7) -- the exact fields verified live in Phase
         *     5.1-5.4: '30 Sept 2020 - 30 June 2026, 24 valuation observations,
         *     quarterly source data' must be reconstructable from these fields alone,
         *     never hard-coded on the frontend.
         */
        DataCoverage: {
            /** Valuation Start */
            valuation_start?: string | null;
            /** Valuation End */
            valuation_end?: string | null;
            /** Valuation Observation Count */
            valuation_observation_count: number;
            /** Transaction Start */
            transaction_start?: string | null;
            /** Transaction End */
            transaction_end?: string | null;
            /** Price Observation Count */
            price_observation_count: number;
            /** Missing Valuation Count */
            missing_valuation_count: number;
            /** Actual Observation Count */
            actual_observation_count: number;
            /** Carried Forward Observation Count */
            carried_forward_observation_count: number;
            /** Estimated Observation Count */
            estimated_observation_count: number;
            /** Unavailable Observation Count */
            unavailable_observation_count: number;
        };
        /**
         * DrawdownAnalytics
         * @description getDrawdowns() -- summary statistics over Phase 3's drawdown_history()
         *     episodes (sec 27/29). All fields are null when there is no drawdown
         *     history at all, never a fabricated zero.
         */
        DrawdownAnalytics: {
            /** Maximum Drawdown Pct */
            maximum_drawdown_pct?: string | null;
            /** Maximum Drawdown Peak */
            maximum_drawdown_peak?: string | null;
            /** Maximum Drawdown Trough */
            maximum_drawdown_trough?: string | null;
            /** Average Drawdown Pct */
            average_drawdown_pct?: string | null;
            /** Episode Count */
            episode_count: number;
            /** Longest Underwater Days */
            longest_underwater_days?: number | null;
            /** Longest Underwater Peak */
            longest_underwater_peak?: string | null;
            /** Fastest Recovery Days */
            fastest_recovery_days?: number | null;
        };
        /** ExtremePeriod */
        ExtremePeriod: {
            /** Label */
            label: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Return Pct */
            return_pct: string;
            /** Absolute Change */
            absolute_change?: string | null;
            /** Opening Value */
            opening_value?: string | null;
            /** Closing Value */
            closing_value?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Database */
            database: boolean;
        };
        /** HighWaterMarkStatus */
        HighWaterMarkStatus: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Current Value */
            current_value?: string | null;
            /** High Water Mark */
            high_water_mark: string;
            /** Distance From High */
            distance_from_high?: string | null;
            /** Distance From High Pct */
            distance_from_high_pct?: string | null;
            /** Days Since High */
            days_since_high?: number | null;
        };
        /** HoldingRow */
        HoldingRow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Security Id */
            security_id: string;
            /** Code */
            code: string;
            /** Units */
            units: string;
            /** Price */
            price?: string | null;
            /** Market Value */
            market_value?: string | null;
            /** Cost Basis */
            cost_basis: string;
            /** Unrealised Gain */
            unrealised_gain?: string | null;
            /** Allocation Pct */
            allocation_pct?: string | null;
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "australian_equities" | "international_equities" | "bonds" | "property" | "cash" | "other" | "unknown";
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "actual" | "calculated" | "estimated" | "unavailable";
            /** Price As At */
            price_as_at?: string | null;
        };
        /** IncomeGrowthRow */
        IncomeGrowthRow: {
            /** Year */
            year: string;
            /** Gross Income */
            gross_income: string;
            /** Growth Pct */
            growth_pct?: string | null;
            /** Decomposition */
            decomposition: string;
        };
        /** IncomeRow */
        IncomeRow: {
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Code */
            code?: string | null;
            /** Dividends */
            dividends?: string | null;
            /** Distributions */
            distributions?: string | null;
            /** Interests */
            interests?: string | null;
            /** Gross Income */
            gross_income: string;
            /** Franking Credits */
            franking_credits: string;
            /** Tax Withheld */
            tax_withheld: string;
            /** Net Income */
            net_income: string;
        };
        /** IncomeYieldResponse */
        IncomeYieldResponse: {
            trailing: components["schemas"]["Metric"];
            forward: components["schemas"]["Metric"];
        };
        /**
         * Metric
         * @description The metadata envelope every analytics figure carries (sec 5) --
         *     mirrors src/analytics/result.py Metric exactly. A metric's availability
         *     must never be inferred from a missing field: `available` and `reason`
         *     are always present, even when `value` is null.
         */
        Metric: {
            /** Name */
            name: string;
            /** Value */
            value?: string | null;
            /** Methodology */
            methodology: string;
            /**
             * Data Quality
             * @enum {string}
             */
            data_quality: "actual" | "calculated" | "estimated" | "limited" | "unavailable";
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Currency */
            currency?: string | null;
            /** Note */
            note?: string | null;
            /** Frequency */
            frequency?: string | null;
            /** Annualisation */
            annualisation?: string | null;
            /** Annualisation Factor */
            annualisation_factor?: string | null;
            /** Risk Free Rate */
            risk_free_rate?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /** Observations */
            observations?: number | null;
            /** Confidence */
            confidence?: ("high" | "medium" | "low" | "none") | null;
            /** Source */
            source: string;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** Milestone */
        Milestone: {
            /** Milestone Id */
            milestone_id: string;
            /** Kind */
            kind: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value?: string | null;
            /** Description */
            description: string;
            /** Portfolio Value */
            portfolio_value?: string | null;
            /** Cumulative Contributions */
            cumulative_contributions?: string | null;
            /** Cumulative Investment Gain */
            cumulative_investment_gain?: string | null;
        };
        /** PerformanceMethodology */
        PerformanceMethodology: {
            /** Return Methodology */
            return_methodology: {
                [key: string]: string;
            };
            twrr: components["schemas"]["TwrrMethodology"];
        };
        /** PerformanceOverview */
        PerformanceOverview: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Opening Value */
            opening_value?: string | null;
            /** Closing Value */
            closing_value?: string | null;
            /** Contributions */
            contributions: string;
            /** Withdrawals */
            withdrawals: string;
            /** Net External Flow */
            net_external_flow: string;
            /** Investment Gain */
            investment_gain?: string | null;
            /** Income */
            income: string;
            /** Fees */
            fees: string;
            /** Total Return */
            total_return?: string | null;
            /** Capital Return */
            capital_return?: string | null;
            /** Income Return */
            income_return?: string | null;
            /** Twrr */
            twrr?: string | null;
            /** Xirr */
            xirr?: string | null;
            /**
             * Data Quality
             * @enum {string}
             */
            data_quality: "actual" | "calculated" | "estimated" | "limited" | "unavailable";
        };
        /**
         * PerformancePeriod
         * @description One entry from getReturns() -- e.g. "1D", "3M", "INCEPTION". A period
         *     the API cannot measure (sec 5's "never let the frontend infer
         *     availability") reports status="unavailable" with `note` stating why,
         *     never a fabricated return.
         */
        PerformancePeriod: {
            /** Label */
            label: string;
            /**
             * As At
             * Format: date
             */
            as_at: string;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Total Return */
            total_return?: string | null;
            /** Capital Return */
            capital_return?: string | null;
            /** Income Return */
            income_return?: string | null;
            /** Twrr */
            twrr?: string | null;
            /** Xirr */
            xirr?: string | null;
            /** Status */
            status: string;
            /** Note */
            note?: string | null;
        };
        /**
         * PortfolioDailyPoint
         * @description One row of the canonical daily series (src/history/generator.py
         *     DailyRow). total_value/securities_value/unrealised_gain are explicitly
         *     nullable -- a day with no computable value is a gap, never a fabricated
         *     zero (Phase 3's own central rule, preserved here rather than re-decided).
         */
        PortfolioDailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total Value */
            total_value?: string | null;
            /** Securities Value */
            securities_value?: string | null;
            /** Cash */
            cash: string;
            /** Cost Basis */
            cost_basis: string;
            /** Invested Capital */
            invested_capital: string;
            /** Realised Gain */
            realised_gain: string;
            /** Unrealised Gain */
            unrealised_gain?: string | null;
            /** Dividends */
            dividends: string;
            /** Distributions */
            distributions: string;
            /** Income */
            income: string;
            /** Fees */
            fees: string;
            /** Cumulative Contributions */
            cumulative_contributions: string;
            /** Cumulative Withdrawals */
            cumulative_withdrawals: string;
            /** High Water Mark */
            high_water_mark: string;
            /** Drawdown Value */
            drawdown_value?: string | null;
            /** Drawdown Pct */
            drawdown_pct?: string | null;
            /** Return Index */
            return_index?: string | null;
            /** Index As At */
            index_as_at?: string | null;
            /** Return High Water */
            return_high_water?: string | null;
            /** Return Drawdown Pct */
            return_drawdown_pct?: string | null;
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "actual" | "calculated" | "estimated" | "unavailable";
            /** Valuation Source */
            valuation_source: string;
            /** Price As At */
            price_as_at?: string | null;
            /** Source Count */
            source_count: number;
            /** Calculation Method */
            calculation_method: string;
        };
        /**
         * PortfolioGrowthPoint
         * @description One day of the canonical growth series (sec 4). `contributions`/
         *     `withdrawals` are this day's own flows, not running totals --
         *     `net_contributions` is the running total (cumulative_contributions +
         *     cumulative_withdrawals; withdrawals are signed negative throughout this
         *     API, matching ContributionHistoryRow). `portfolio_value`/
         *     `investment_gain` are null together whenever this date has no
         *     computable valuation -- never a fabricated 0 on a gap day.
         *
         *     `period_investment_gain` is this day's own gain/loss (not cumulative):
         *     balance[t] - balance[t-1] - (contributions[t] + withdrawals[t]). This
         *     is the value the chart's Investment Gain/Investment Loss areas plot --
         *     positive renders as a solid bright-green area above the zero baseline,
         *     negative as solid bright-red below it; the two are mutually exclusive
         *     at every point, and neither is ever labelled with the other's colour.
         */
        PortfolioGrowthPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Portfolio Value */
            portfolio_value?: string | null;
            /** Contributions */
            contributions: string;
            /** Withdrawals */
            withdrawals: string;
            /** Net Contributions */
            net_contributions: string;
            /** Investment Gain */
            investment_gain?: string | null;
            /** Period Investment Gain */
            period_investment_gain?: string | null;
            /**
             * Cash Flow Events
             * @default []
             */
            cash_flow_events: components["schemas"]["CashFlowEvent"][];
        };
        /**
         * PortfolioGrowthSummary
         * @description The headline split (sec 8): current value, what was actually put in,
         *     and the simple dollar difference between them. `growth_pct` is
         *     investment_gain/net_contributions -- deliberately not called a "return"
         *     (sec 9): it does not account for when money arrived, unlike TWRR/XIRR,
         *     which live at /api/portfolio/performance and /performance/methodology.
         */
        PortfolioGrowthSummary: {
            /** Current Value */
            current_value?: string | null;
            /** Net Contributions */
            net_contributions: string;
            /** Investment Gain */
            investment_gain?: string | null;
            /** Growth Pct */
            growth_pct?: string | null;
            /**
             * As At
             * Format: date
             */
            as_at: string;
        };
        /** PortfolioOverview */
        PortfolioOverview: {
            /** As At */
            as_at?: string | null;
            /** Current Value */
            current_value?: string | null;
            /** Total Contributed */
            total_contributed: string;
            /** Total Withdrawn */
            total_withdrawn: string;
            /** Net Contributed */
            net_contributed: string;
            /** Investment Growth */
            investment_growth?: string | null;
            /** Income Received */
            income_received: string;
            data_coverage: components["schemas"]["DataCoverage"];
        };
        /**
         * PortfolioState
         * @description A daily point plus the holdings that made it up -- what
         *     getHoldings()/portfolio_state() returns for one date.
         */
        PortfolioState: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total Value */
            total_value?: string | null;
            /** Securities Value */
            securities_value?: string | null;
            /** Cash */
            cash: string;
            /** Cost Basis */
            cost_basis: string;
            /** Invested Capital */
            invested_capital: string;
            /** Realised Gain */
            realised_gain: string;
            /** Unrealised Gain */
            unrealised_gain?: string | null;
            /** Dividends */
            dividends: string;
            /** Distributions */
            distributions: string;
            /** Income */
            income: string;
            /** Fees */
            fees: string;
            /** Cumulative Contributions */
            cumulative_contributions: string;
            /** Cumulative Withdrawals */
            cumulative_withdrawals: string;
            /** High Water Mark */
            high_water_mark: string;
            /** Drawdown Value */
            drawdown_value?: string | null;
            /** Drawdown Pct */
            drawdown_pct?: string | null;
            /** Return Index */
            return_index?: string | null;
            /** Index As At */
            index_as_at?: string | null;
            /** Return High Water */
            return_high_water?: string | null;
            /** Return Drawdown Pct */
            return_drawdown_pct?: string | null;
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "actual" | "calculated" | "estimated" | "unavailable";
            /** Valuation Source */
            valuation_source: string;
            /** Price As At */
            price_as_at?: string | null;
            /** Source Count */
            source_count: number;
            /** Calculation Method */
            calculation_method: string;
            /**
             * Holdings
             * @default []
             */
            holdings: components["schemas"]["HoldingRow"][];
        };
        /**
         * PortfolioValueReconciliationCheck
         * @description One reconciliation row (sec 10): calculated portfolio value/cash on a
         *     date vs. what Vanguard's own statement reported for that same date.
         *     `status` is SKIP when there was nothing to compare against (e.g. no
         *     reported cash balance on that particular statement) -- distinct from
         *     FAIL, which means a real, calculated discrepancy exists.
         */
        PortfolioValueReconciliationCheck: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Subject */
            subject: string;
            /** Calculated */
            calculated?: string | null;
            /** Source */
            source?: string | null;
            /** Difference */
            difference?: string | null;
            /** Tolerance */
            tolerance: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FAIL" | "SKIP";
        };
        /** RealisedGainSummary */
        RealisedGainSummary: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Realised Gain */
            realised_gain: string;
            /** Realised Loss */
            realised_loss: string;
            /** Net Realised Gain */
            net_realised_gain: string;
        };
        /**
         * ReconciliationResult
         * @description Sec 8/hardening sec 3's exact vocabulary. reconciliation_status is
         *     always derived from residual/tolerance upstream (src/analytics/
         *     attribution.py) -- this model only describes that contract, it does not
         *     re-derive it. Legacy aliases (difference/status) are retained since nothing
         *     downstream should need to change to stop reading them, but attributed_change/
         *     actual_change/residual/reconciliation_status/tolerance are the primary,
         *     documented fields (sec 8: 'do not reintroduce alternative terminology' --
         *     meaning these five names are authoritative, not the aliases).
         */
        ReconciliationResult: {
            /** Attributed Change */
            attributed_change?: string | null;
            /** Actual Change */
            actual_change?: string | null;
            /** Residual */
            residual?: string | null;
            /** Tolerance */
            tolerance: string;
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "PASS" | "FAIL" | "LIMITED";
            /** Opening Value */
            opening_value?: string | null;
            /** Closing Value */
            closing_value?: string | null;
            /** External Flows */
            external_flows?: string | null;
            /** Note */
            note?: string | null;
            /** Difference */
            difference?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FAIL" | "LIMITED";
        };
        /** RiskMetrics */
        RiskMetrics: {
            volatility: components["schemas"]["Metric"];
            sharpe_ratio: components["schemas"]["Metric"];
            sortino_ratio: components["schemas"]["Metric"];
        };
        /** RollingIncomeYieldPoint */
        RollingIncomeYieldPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Yield */
            yield?: string | null;
            /** Status */
            status: string;
        };
        /**
         * RollingReturnPoint
         * @description One point of getRolling(metric='return') -- src/analytics/rolling.py
         *     RollingPoint. `is_estimate` is explicit rather than a silently
         *     carried-forward window edge (sec 9).
         */
        RollingReturnPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value?: string | null;
            /** Window Days */
            window_days: number;
            /** Is Estimate */
            is_estimate: boolean;
        };
        /** RollingVolatilityPoint */
        RollingVolatilityPoint: {
            /**
             * As At
             * Format: date
             */
            as_at: string;
            /** Volatility */
            volatility?: string | null;
            /** Window Quarters */
            window_quarters: number;
            /** Observations */
            observations: number;
            /** Frequency */
            frequency: string;
            /** Annualisation Factor */
            annualisation_factor: string;
            /** Data Quality */
            data_quality: string;
        };
        /**
         * SecurityAttributionRow
         * @description A security's OWN return (total_return) is kept distinct from its
         *     SHARE of the portfolio's return (portfolio_contribution) -- collapsing
         *     these into one field was the exact confusion sec 7 (Phase 4) exists to
         *     prevent: a small, high-return holding must show a high own-return and a
         *     small contribution, never the same number for both.
         */
        SecurityAttributionRow: {
            /** Security Id */
            security_id: string;
            /** Code */
            code: string;
            /** Opening Value */
            opening_value: string;
            /** Closing Value */
            closing_value: string;
            /** Capital Gain */
            capital_gain: string;
            /** Income */
            income: string;
            /** Fees */
            fees: string;
            /** Total Return */
            total_return?: string | null;
            /** Portfolio Contribution */
            portfolio_contribution?: string | null;
            /** Portfolio Weight */
            portfolio_weight?: string | null;
        };
        /**
         * TwrrMethodology
         * @description Preserves the exact vocabulary sec 8 calls out by name --
         *     SUBPERIOD_LINKED / EXACT_DATED must never be simplified away, since they
         *     are the frontend's only way to distinguish this dataset's approximation
         *     of TWRR from a true one (see docs/analytics.md 'Why quarterly risk
         *     metrics' and docs/api.md).
         */
        TwrrMethodology: {
            /**
             * Twrr Methodology
             * @constant
             */
            twrr_methodology: "SUBPERIOD_LINKED";
            /** Twrr Methodology Note */
            twrr_methodology_note: string;
            /**
             * Cash Flow Adjustment Method
             * @constant
             */
            cash_flow_adjustment_method: "EXACT_DATED";
            /** Cash Flow Adjustment Note */
            cash_flow_adjustment_note: string;
            /**
             * Cash Flow Observation Quality
             * @enum {string}
             */
            cash_flow_observation_quality: "LIMITED" | "SUFFICIENT";
            /** Valuation Observation Count */
            valuation_observation_count: number;
        };
        /** UnrealisedGainSnapshot */
        UnrealisedGainSnapshot: {
            /** Security Id */
            security_id: string;
            /** Code */
            code: string;
            /** Asset Class */
            asset_class: string;
            /** Market Value */
            market_value?: string | null;
            /** Cost Basis */
            cost_basis: string;
            /** Unrealised Gain */
            unrealised_gain?: string | null;
            /** Unrealised Gain Pct */
            unrealised_gain_pct?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    overview_api_portfolio_overview_get: {
        parameters: {
            query?: {
                as_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_portfolio_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Capability"];
                    };
                };
            };
        };
    };
    coverage_api_portfolio_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCoverage"];
                };
            };
        };
    };
    performance_api_portfolio_performance_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_for_year_api_portfolio_performance_year__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_periods_api_portfolio_performance_periods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformancePeriod"][];
                };
            };
        };
    };
    performance_methodology_api_portfolio_performance_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceMethodology"];
                };
            };
        };
    };
    history_api_portfolio_history_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDailyPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_growth_api_portfolio_growth_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioGrowthPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_growth_summary_api_portfolio_growth_summary_get: {
        parameters: {
            query?: {
                as_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioGrowthSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_growth_reconciliation_api_portfolio_growth_reconciliation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioValueReconciliationCheck"][];
                };
            };
        };
    };
    holdings_api_portfolio_holdings_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioState"] | components["schemas"]["HoldingRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holding_history_api_portfolio_holdings__code__history_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allocation_api_portfolio_allocation_get: {
        parameters: {
            query?: {
                by?: string;
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allocation_history_api_portfolio_allocation_history_get: {
        parameters: {
            query?: {
                by?: string;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationHistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    concentration_api_portfolio_concentration_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcentrationSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    income_api_portfolio_income_get: {
        parameters: {
            query?: {
                granularity?: string;
                by_security?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    income_yield_api_portfolio_income_yield_get: {
        parameters: {
            query?: {
                as_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeYieldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    income_growth_api_portfolio_income_growth_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeGrowthRow"][];
                };
            };
        };
    };
    contributions_api_portfolio_contributions_get: {
        parameters: {
            query?: {
                as_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contributions_history_api_portfolio_contributions_history_get: {
        parameters: {
            query?: {
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    realised_gains_api_portfolio_gains_realised_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealisedGainSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unrealised_gains_api_portfolio_gains_unrealised_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnrealisedGainSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attribution_api_portfolio_attribution_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    security_attribution_api_portfolio_attribution_securities_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityAttributionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attribution_reconciliation_api_portfolio_attribution_reconciliation_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionReconciliationPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_api_portfolio_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskMetrics"];
                };
            };
        };
    };
    risk_benchmark_api_portfolio_risk_benchmark_get: {
        parameters: {
            query?: {
                period?: string;
                benchmark_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drawdowns_api_portfolio_drawdowns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawdownAnalytics"];
                };
            };
        };
    };
    high_water_mark_api_portfolio_drawdowns_high_water_mark_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighWaterMarkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rolling_api_portfolio_risk_rolling_get: {
        parameters: {
            query?: {
                metric?: string;
                window_days?: number;
                window_quarters?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollingReturnPoint"][] | components["schemas"]["RollingVolatilityPoint"][] | components["schemas"]["RollingIncomeYieldPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_portfolio_calendar_get: {
        parameters: {
            query?: {
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarPerformanceRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_worst_api_portfolio_best_worst_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ExtremePeriod"][] | string;
                    };
                };
            };
        };
    };
    milestones_api_portfolio_milestones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Milestone"][];
                };
            };
        };
    };
    activity_api_portfolio_activity_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
