"""The Portfolio Growth dataset (Step 9): the canonical, single-source view
answering "how much did I put in, and how much of what I have now was
actually generated by the investments?"

Nothing here is a new financial calculation -- every field is either read
directly from src/history's own daily series (Phase 3, itself built from
Phase 2's ledger) or a derived subtraction Step 9 itself defines:

    net_contributions      = cumulative_contributions + cumulative_withdrawals
    investment_gain        = portfolio_value - net_contributions            (cumulative, since inception)
    period_investment_gain = investment_gain[t] - investment_gain[t-1]      (this day's own gain/loss)

period_investment_gain is algebraically the same quantity a later chart
update's own formula names directly: balance[t] - balance[t-1] -
(contributions[t] + withdrawals[t]) -- see portfolio_growth()'s inline
comment for the identity that makes the two expressions equal.

(withdrawals are stored as a running *negative* total throughout this
codebase -- see ContributionSummary.net_contributed in contributions.py,
which does the same `total_in + total_out` addition -- so "+" here is the
same subtraction Step 9's spec describes, just consistent with the sign
convention every other screen already uses.)

This module also assembles the reconciliation view (Step 9 sec 10) by
reusing src/engine/reconciliation.py's existing Reconciler unchanged --
that engine already checks calculated portfolio value/cash against what
Vanguard reported, per date; this only reshapes its output for the API.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date, timedelta
from decimal import Decimal

from src.analytics.contributions import contribution_efficiency, contribution_summary
from src.database.repository import Repository
from src.engine.config import DEFAULT_CONFIG, EngineConfig
from src.engine.ledger import Ledger
from src.engine.reconciliation import Reconciler
from src.history.config import Granularity
from src.history.service import HistoryService

ZERO = Decimal("0")

# Source transaction types that are cash-flow events for this dataset (sec
# 3: contributions and withdrawals as first-class portfolio events). BUY/
# SELL/DIVIDEND/etc are not -- money moving between cash and securities, or
# income arriving, is not the investor adding or removing money.
_DEPOSIT_TYPES = ("DEPOSIT",)
_WITHDRAWAL_TYPES = ("WITHDRAWAL",)


@dataclass(frozen=True)
class CashFlowEvent:
    """One contribution or withdrawal, traceable back to its own source
    transaction (sec 11: data provenance) -- `transaction_id` is the same id
    src/models.Transaction assigned it at ingestion."""
    transaction_id: str
    date: date
    type: str          # "CONTRIBUTION" | "WITHDRAWAL"
    amount: Decimal     # signed: positive = contribution, negative = withdrawal
    account: str
    source: str
    description: str | None = None


@dataclass(frozen=True)
class GrowthPoint:
    date: date
    portfolio_value: Decimal | None   # None = no computable valuation this day (a gap, never 0)
    contributions: Decimal            # this day's contributions only, not cumulative
    withdrawals: Decimal              # this day's withdrawals only (signed negative), not cumulative
    net_contributions: Decimal        # cumulative net -- see module docstring
    investment_gain: Decimal | None   # None whenever portfolio_value is None
    # This day's own investment gain/loss (not cumulative): balance[t] -
    # balance[t-1] - (contributions[t] + withdrawals[t]). Equivalently, and
    # how this is actually computed below, the day-over-day difference of
    # the cumulative `investment_gain` sequence -- the two are
    # algebraically identical since net_contributions[t] -
    # net_contributions[t-1] = contributions[t] + withdrawals[t] by
    # construction. None whenever either day's investment_gain is None (a
    # valuation gap on either side breaks the delta, rather than silently
    # bridging it).
    period_investment_gain: Decimal | None
    cash_flow_events: list[CashFlowEvent] = field(default_factory=list)


@dataclass(frozen=True)
class GrowthSummary:
    """The headline split for a Portfolio Growth screen (sec 8): built
    entirely by re-reading contributions.py's own ContributionSummary/
    ContributionEfficiency, not by recomputing either."""
    current_value: Decimal | None
    net_contributions: Decimal
    investment_gain: Decimal | None
    # Deliberately not "annualised return" (sec 9) -- see
    # ContributionEfficiency's own docstring for why gain-per-dollar is not
    # a return methodology.
    growth_pct: Decimal | None
    as_at: date


@dataclass(frozen=True)
class ReconciliationCheck:
    """One reconciliation row (sec 10), the API-facing reshaping of
    src/engine/reconciliation.py's Check dataclass -- same numbers, contract
    vocabulary (`source`/`calculated`/`difference`/`status`) matched to the
    Step 9 spec rather than the engine's own internal naming."""
    date: date
    subject: str
    calculated: Decimal | None
    source: Decimal | None
    difference: Decimal | None
    tolerance: Decimal
    status: str  # PASS | FAIL | SKIP


def _cash_flow_events(repo: Repository, start: date | None, end: date | None
                      ) -> dict[str, list[CashFlowEvent]]:
    clauses, params = ["t.type IN ('DEPOSIT','WITHDRAWAL')"], []
    if start:
        clauses.append("t.trade_date >= ?"); params.append(start.isoformat())
    if end:
        clauses.append("t.trade_date <= ?"); params.append(end.isoformat())
    rows = repo.rows(
        "SELECT t.transaction_id, t.trade_date, t.type, t.net_amount,"
        " t.description, a.label AS account FROM transactions t"
        " JOIN accounts a USING (account_id)"
        f" WHERE {' AND '.join(clauses)} ORDER BY t.trade_date, t.transaction_id",
        tuple(params))

    by_date: dict[str, list[CashFlowEvent]] = defaultdict(list)
    for r in rows:
        amount = Decimal(r["net_amount"]) if r["net_amount"] is not None else ZERO
        by_date[r["trade_date"]].append(CashFlowEvent(
            transaction_id=r["transaction_id"],
            date=date.fromisoformat(r["trade_date"]),
            type="CONTRIBUTION" if r["type"] in _DEPOSIT_TYPES else "WITHDRAWAL",
            amount=amount,
            account=r["account"],
            source="VANGUARD",
            description=r["description"] or None,
        ))
    return by_date


def portfolio_growth(history: HistoryService, repo: Repository,
                     start: date | None = None, end: date | None = None
                     ) -> list[GrowthPoint]:
    """The canonical time-series dataset (sec 4), for an arbitrary date
    range. Every point's cumulative fields come straight from
    portfolio_daily (Phase 3); this only derives the Step-9-defined
    quantities and attaches that day's own cash-flow events."""
    daily = history.portfolio_history(start, end, Granularity.DAILY)
    if not daily:
        return []

    events = _cash_flow_events(repo, start, end)

    # The requested window may not start at the very first day of history,
    # so this day's *delta* contribution/withdrawal (and its period
    # investment gain/loss, which is itself a delta) needs the previous
    # day's cumulative totals even when that previous day is outside
    # [start, end].
    previous_in = previous_out = ZERO
    previous_gain: Decimal | None = None
    if start:
        before = history.portfolio_history(None, start - timedelta(days=1), Granularity.DAILY)
        if before:
            last = before[-1]
            previous_in = Decimal(last["cumulative_contributions"])
            previous_out = Decimal(last["cumulative_withdrawals"])
            before_value = Decimal(last["total_value"]) if last["total_value"] is not None else None
            previous_gain = (before_value - (previous_in + previous_out)) if before_value is not None else None

    points: list[GrowthPoint] = []
    for row in daily:
        total_in = Decimal(row["cumulative_contributions"])
        total_out = Decimal(row["cumulative_withdrawals"])
        net_contributions = total_in + total_out  # see module docstring re: sign
        value = Decimal(row["total_value"]) if row["total_value"] is not None else None
        investment_gain = (value - net_contributions) if value is not None else None
        period_gain = (
            (investment_gain - previous_gain)
            if investment_gain is not None and previous_gain is not None
            else None
        )

        points.append(GrowthPoint(
            date=date.fromisoformat(row["date"]),
            portfolio_value=value,
            contributions=total_in - previous_in,
            withdrawals=total_out - previous_out,
            net_contributions=net_contributions,
            investment_gain=investment_gain,
            period_investment_gain=period_gain,
            cash_flow_events=events.get(row["date"], []),
        ))
        previous_in, previous_out, previous_gain = total_in, total_out, investment_gain

    return points


def portfolio_growth_summary(history: HistoryService, as_at: date | None = None) -> GrowthSummary:
    """Re-reads contributions.py's own summary/efficiency rather than
    recomputing either (sec 8: "the exact layout should follow the existing
    design system" -- the exact *numbers* follow the existing analytics
    layer, for the same reason)."""
    summary = contribution_summary(history, as_at)
    efficiency = contribution_efficiency(history, as_at)
    return GrowthSummary(
        current_value=summary.current_value,
        net_contributions=summary.net_contributed,
        investment_gain=summary.investment_growth,
        growth_pct=efficiency.gain_per_dollar_contributed,
        as_at=summary.as_at,
    )


def growth_reconciliation(repo: Repository, ledger: Ledger,
                          config: EngineConfig = DEFAULT_CONFIG) -> list[ReconciliationCheck]:
    """Opening balance + contributions + investment movements - withdrawals
    - fees = closing balance (sec 10), reusing the engine's own Reconciler
    exactly -- this function performs no reconciliation logic of its own,
    only reshapes Check -> ReconciliationCheck. Only the portfolio-value and
    cash checks are relevant to a growth screen; per-security unit checks
    are Holdings' concern (already surfaced there via a different path)."""
    from src.engine.cash import opening_cash_for
    from src.engine.prices import SnapshotPriceSource

    prices = SnapshotPriceSource.from_repository(repo)
    reconciler = Reconciler(repo, prices, config, opening_cash_for(repo))
    checks = reconciler.run(ledger)
    return [
        ReconciliationCheck(
            date=c.when, subject=c.subject, calculated=c.calculated,
            source=c.expected, difference=c.difference, tolerance=c.tolerance,
            status=c.status,
        )
        for c in checks if c.subject in ("portfolio value", "cash")
    ]
